POST http://127.0.0.1:9999/user HTTP/1.1
Content-Type: application/json

{
  "username": "LiMing",
  "password": "lmaaaecerrv3u4"
}

###
GET http://127.0.0.1:9999/user

###
GET http://127.0.0.1:9999/user/1

###
PUT http://127.0.0.1:9999/user/1 HTTP/1.1
Content-Type: application/json

{
  "password": "wmz1234567890"
}


###
GET http://127.0.0.1:9999/forward/user